# Generated by Django 3.1.4 on 2020-12-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='logged',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='typeU',
            field=models.IntegerField(default=0),
        ),
    ]
