# Generated by Django 3.1.4 on 2020-12-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange_app', '0002_remove_transaction_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='category',
        ),
        migrations.RemoveField(
            model_name='user',
            name='mobile_num',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(null=True),
        ),
    ]
