# Generated by Django 3.1.4 on 2020-12-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('currency_exchange_app', '0003_auto_20201226_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='logged',
        ),
        migrations.RemoveField(
            model_name='user',
            name='type',
        ),
    ]
